import Head from "next/head"
import css from "styled-jsx/css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "#B8CEC2",
            padding: "1rem" ,
          }}
        >
        <h1>Head</h1>
        </header>
        <a>{children}</a>
        <footer
          style= {{
            backgroundColor: "#EFF4F8",
            padding: "1 rem"
          }}
        >
        <h3>Footer</h3>
        </footer>
      </body>
    </html>
    
    
  )
}
